### ISSUE TITLE
config help

### ISSUE THREAD

**Issue by unused** [flocko/taskrunners#2]
what is the path for I have to configure and why is the IP of the box needed?

**Comment by flocko** [comment]
the path variable is needed if you have your magento installed in a subdirectory of your box:
for example in ```/var/www/magento```

just use ```path: '/'``` or empty string if your magento installation resides in the main directory of your box.

the IP of your box is needed so that browserSync can establish a proxy for other devices in the same network.

**Comment by unused** [comment]
:+1:
